# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_auto_20180323_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='ano',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carro',
            name='modelo',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='carro',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
