# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0004_auto_20180323_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='caracteristicas',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
